import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

interface PDFOptions {
  taskId: number;
  taskTitle: string;
  propertyAddress: string;
  cleanerName: string;
  completedAt: string;
  photos: { url: string; photoType: string; caption?: string }[];
  checklists: { title: string; isCompleted: boolean }[];
  notes: { content: string; noteType: string }[];
  issues: { content: string; severity: string; category: string }[];
}

export async function generatePDFBuffer(options: PDFOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Cover Page
    doc.fontSize(24).font('Helvetica-Bold').text('MayaOps Cleaning Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).font('Helvetica').text(`Task ID: ${options.taskId}`, { align: 'center' });
    doc.text(`Property: ${options.propertyAddress}`, { align: 'center' });
    doc.text(`Cleaner: ${options.cleanerName}`, { align: 'center' });
    doc.text(`Completed: ${new Date(options.completedAt).toLocaleString()}`, { align: 'center' });
    doc.moveDown(2);

    // Task Title
    doc.fontSize(18).font('Helvetica-Bold').text(options.taskTitle);
    doc.moveDown();

    // Checklist Section
    if (options.checklists.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Checklist Acknowledgment');
      doc.fontSize(10).font('Helvetica');
      options.checklists.forEach((item) => {
        doc.text(`${item.isCompleted ? '✓' : '☐'} ${item.title}`);
      });
      doc.moveDown();
    }

    // Issues Section
    if (options.issues.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Reported Issues');
      doc.fontSize(10).font('Helvetica');
      options.issues.forEach((issue) => {
        doc.text(`[${issue.severity}] ${issue.category}: ${issue.content}`);
      });
      doc.moveDown();
    }

    // Notes Section
    if (options.notes.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Notes');
      doc.fontSize(10).font('Helvetica');
      options.notes.forEach((note) => {
        doc.text(`• ${note.content}`);
      });
      doc.moveDown();
    }

    // Photo Evidence Section
    doc.addPage();
    doc.fontSize(16).font('Helvetica-Bold').text('Photo Evidence');
    doc.moveDown();

    const beforePhotos = options.photos.filter((p) => p.photoType === 'before');
    const afterPhotos = options.photos.filter((p) => p.photoType === 'after');

    doc.fontSize(12).font('Helvetica-Bold').text(`Before Photos: ${beforePhotos.length}`);
    doc.fontSize(10).font('Helvetica');
    beforePhotos.forEach((photo, idx) => {
      doc.text(`${idx + 1}. ${photo.caption || 'No caption'}`);
      doc.fontSize(8).text(`   URL: ${photo.url}`);
      doc.fontSize(10); // Reset to previous size
    });
    doc.moveDown();

    doc.fontSize(12).font('Helvetica-Bold').text(`After Photos: ${afterPhotos.length}`);
    doc.fontSize(10).font('Helvetica');
    afterPhotos.forEach((photo, idx) => {
      doc.text(`${idx + 1}. ${photo.caption || 'No caption'}`);
      doc.fontSize(8).text(`   URL: ${photo.url}`);
      doc.fontSize(10); // Reset to previous size
    });

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).font('Helvetica').text('Generated by MayaOps', { align: 'center' });
    doc.text(`Report Date: ${new Date().toLocaleString()}`, { align: 'center' });

    doc.end();
  });
}

export function generatePDFChecksum(buffer: Buffer): string {
  const crypto = require('crypto');
  return crypto.createHash('sha256').update(buffer).digest('hex');
}
